# After changing this file, check it on:
# http://lint.travis-ci.org/
notifications:
  email:
    on_success: always
    on_failure: never

# requiere sudo?
sudo: false

# donde se almacena las cosas
cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip

language: python

# version de python
python:
  - "3.3"

# instalar las dependencias
before_install:
# Instalar miniconda para evitar compilar scipy y agilizar el tramite
  - mkdir -p download #carpeta donde guardar las cosas
  - cd download
  - wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - cd ..
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda # fin de la instalacion de conda
  - pip install Theano # instalando theano

addons:
  apt_packages:
   - texlive-latex-recommended
   - texlive-latex-extra
   - texlive-fonts-recommended
   - dvipng

install:
  # se crea en enviroment para python para que no interfiera con nada mas
  - conda create --yes -q -n pyenv mkl python=3.3 numpy=1.9.1 scipy=0.14.0 nose=1.3.4 pyparsing=1.5 pip flake8=2.3 six=1.9.0 pep8=1.6.2 pyflakes=0.8.1 sphinx
  - source activate pyenv
  - pip install . --no-deps # instala cupydle
  - chmod +x cupydle/test/mnist/get_data.sh

# command to run tests
env:
  - PART="theano/tests/test_flake8.py" DOC=1
  - PART="-e test_flake8.py theano/compat theano/compile theano/d3viz theano/gof theano/misc theano/sandbox theano/scalar theano/scan_module theano/sparse theano/tests theano/typed_list"
  - PART="theano/tensor"

matrix:
  fast_finish: true
  include:
    - python: "3.3"
      env: PART="." THEANO_FLAGS="mode=FAST_COMPILE"

script:
  - export THEANO_FLAGS=$THEANO_FLAGS,warn.ignore_bug_before=all,on_opt_error=raise,on_shape_error=raise,gcc.cxxflags=-pipe
  - pip install Theano
  - python --version
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  # Move out of Theano so the import will use the installed version
  - cd ..
  - pip list
  - pip show Theano
  - ls -lh
  - python -c 'import cupydle'
  #- pip install Theano
  # Move to the path of the installed version
  #- cd $(python -c 'import theano; import os; print(os.path.split(theano.__file__)[0])')
  #- cd -; cd lerker
  - python -c 'import theano; print(theano.config)'
  - ls -l cupydle
  #- python cupydle/cupydle/test/mlp_MNIST.py

after_failure:
  - cat /home/travis/.pip/pip.log





