sudo: false
language: python
python:
  - "3.5"
install:
  - "pip install numpy"
  - "pip install matplotlib"
script:
  - cd ..
  - ls
  - python cupydle/test/xor_demo.py
#after_success:
#  - coveralls
