#!/bin/bash
echo "Folder s1 ------------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s1/f1/');exit"
echo "Folder s2 ------------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s2/f1ita/');exit"
echo "Folder s3/f1eng-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s3/f1eng/');exit"
echo "Folder s3/f2per-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s3/f2per/');exit"
echo "Folder s3/f3per- -----------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s3/f3per/');exit"
echo "Folder s4/f1eng-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s4/f1eng/');exit"
echo "Folder s4/f2chi-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s4/f2chi/');exit"
echo "Folder s4/f3chi-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s4/f3chi/');exit"	
echo "Folder s4/f4chi-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s4/f4chi/');exit"
echo "Folder s4/f5nhn-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s4/f5hnh/');exit"
echo "Folder s5/f1eng-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s5/f1eng/');exit"
echo "Folder s5/f2eng-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s5/f2eng/');exit"
echo "Folder s5/f3per-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s5/f3per/');exit"
echo "Folder s6/ff1eng------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s6/f1eng/');exit"
echo "Folder s6/f2urd-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s6/f2urd/');exit"
echo "Folder s6/f3urd-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s6/f3urd/');exit"
echo "Folder s7/f1eng-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s7/f1eng/');exit"
echo "Folder s7/f2urd-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s7/f2urd/');exit"
echo "Folder s7/f3pjb-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s7/f3pjb/');exit"
echo "Folder s7/f4urd-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s7/f4urd/');exit"
echo "Folder s8/f1eng-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s8/f1eng/');exit"
echo "Folder s8/f2sdh-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s8/f2sdh/');exit"
echo "Folder s8/f3chi-------------------------------------------------------------------------------"
matlab -nodesktop -nosplash -r "get_audio_features('~/Pruebas/RML_Emotion_Database_audio/s8/f3chi/');exit"
